flaskbook/apps/crud/models.py
from datetime import datetime

from apps.app import db
from werkzeug.security import generate_password_hash


class User(db.Model):
    # テーブル名を指定
    __tablename__ = "users"
    # 　カラムを定義する
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)    

    # 　パスワードをリセットするためのプロパティ
    @property
    def password(self):
        raise AttributeError("読み取り不可")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

flaskbook/apps/crud/forms.py
from flask_wtf import FlaskForm 
from wtforms import PasswordField, StringField, SubmitField 
from wtforms.validators import DataRequired, Email, length 

# ユーザ新規作成とユーザ編集フォームクラス
class UserForm(FlaskForm):
    #ユーザーフォームのusername属性のラベルとバリデータを設定する
    username = StringField(
        "ユーザー名",
        validators = [
            DataRequired(message="ユーザー名は必須です。"),
            length(max=30, message="30文字以内で入力してください。"),
        ],
    )
    # ユーザーフォームemail属性のラベルとバリデータを設定する
    email = StringField(
        "メールアドレス",
        validators = [
            DataRequired(message="メールアドレスは必須です。"),
            Email(message="メールアドレスの形式で入力してください。"),
        ],
    )
    # ユーザーフォームpassword属性のラベルとバリデータを設定する
    password = PasswordField(
        "パスワード",
        validators=[DataRequired(message="パスワードは必須です。")]
    )
    # ユーザーフォームsubmit属性の文言を設定する
    submit = SubmitField("新規登録")
    

flaskbook/apps/crud/__init__.py
import apps.crud.models

flaskbook/apps/crud/views.py
from apps.crud.forms import UserForm
from flask import Blueprint, render_template, redirect, url_for

# Blueprintでcrudアプリを生成する
crud = Blueprint("crud", __name__, template_folder="templates", static_folder="static")


# indexエンドポイントを作成し、index.htmlを返す
@crud.route("/")
def index():
    return render_template("crud/index.html")

# dbをimportする
from apps.app import db

# Userクラスをimportする
from apps.crud.models import User


@crud.route("/sql")
def sql():
    db.session.query(User).order_by("username").all()
    return "コンソールログを確認してください"


@crud.route("/users/new", methods=["GET", "POST"])
def create_user():
    # UserFormをインスタンス化する
    form = UserForm()
    if form.validate_on_submit():
        # ユーザーを作成する
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )
        # ユーザーを追加してコミットする
        db.session.add(user)
        db.session.commit()
        # ユーザーの一覧画面へリダイレクトする
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)


@crud.route("/users")
def users():
    """ユーザの一覧を取得する"""
    users = User.query.all()
    return render_template("crud/index.html", users=users)


@crud.route("/users/<user_id>", methods=["GET", "POST"])
def edit_user(user_id):
    form = UserForm()

    # Userモデルを利用してユーザを取得する
    user = User.query.filter_by(id=user_id).first()

    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))

    # GETの場合はHTMLを返す
    return render_template("crud/edit.html", form=form, user=user)

flaskbook/apps/crud/templates/crud/create.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>ユーザー新規作成</title>
    </head>

    <body>
        <h2>ユーザー新規作成</h2>
        <form action="{{url_for('crud.create_user')}}" method="POST" novalidate="novalidate">
            {{ form.csrf_token}}
            <p>
                {{ form.username.label}} 
                {{ form.username(placeholder="ユーザー名")}} 
            </p>
            {% for error in form.username.errors %}
            <span style="color: red;">{{error}}</span>
            {% endfor %}
            <p>
                {{ form.email.label}} 
                {{ form.email(placeholder="メールアドレス")}}
            </p>
            {% for error in form.email.errors %}
            <span style="color: red;">{{error}}</span>
            {% endfor %}
            <p>
                {{ form.password.label}} 
                {{ form.password(placeholder="パスワード")}}
            </p>
            {% for error in form.password.errors %}
            <span style="color: red;">{{error}}</span>
            {% endfor %}
            <p>{{ form.submit() }}</p>
        </form>
    </body>
</html>

flaskbook/apps/crud/templates/crud/edit.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>ユーザー編集</title>
        <link 
            rel="stylesheet" 
            href="{{ url_for('crud.static', filename='style.css') }}"
        />
    </head>

    <body>
        <h2>ユーザー編集</h2>

        <form
        action="{{url_for('crud.edit_user', user_id=user.id)}}"
        method="POST"
        novalidated="novalidate"
        >

            {{ form.csrf_token}}
            <p>
                {{ form.username.label }}
                {{ form.username(placeholder="ユーザー名", value=user.username) }}
            </p>
            {% for error in form.username.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
            <p> 
                {{ form.email.label }}
                {{ form.email(placeholder="メールアドレス", value=user.email) }}
            </p>
            {% for error in form.email.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
            <p> 
                {{ form.password.label }}
                {{ form.password(placeholder="パスワード") }}
            </p>
            {% for error in form.password.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
            <p>
                {{ form.password.label }} {{ form.password(placeholders="パスワード") }}
            </p>
            {% for error in form.password.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
            <p><input type="submit" value="更新" /></p>
        </form>
    </body>
</html>

flaskbook/apps/crud/templates/crud/index.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>ユーザの一覧</title>
        <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css') }}" />
    </head>

    <body>
        <h2>ユーザの一覧</h2>

        <a href="{{ url_for('crud.create_user') }}">ユーザ新規作成</a>

        <table>
            <tr>
                <th>ユーザID</th>
                <th>ユーザ名</th>
                <th>メールアドレス</th>
            </tr>
            {% for user in users %}
            <tr>
                <td><a href="{{ url_for('crud.edit_user', user_id=user.id) }}">{{ user.id }}</a></td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
            </tr>
            {% endfor %}
        </table>
    <body>
</html>